### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by theomart77**

### CODE REVIEW

**Review by Yodag7354 — APPROVED** [review]
theomart77:main

**Comment by chrispy1174** [comment]
I really appreciate the help but i’m still losted from trying to learn code, recover assets and not go homeless. Do you think you could personal help me some more please

**Review by Yodag7354 — APPROVED** [review]

**Review by ttloves2 — APPROVED** [review]

**Review by syarulyusoff — APPROVED** [review]

**Review by Anfpara — APPROVED** [review]

**Comment by chrispy1174** [comment]
Thanks

**Comment by chrispy1174** [comment]
Whey could you help me get or explain to me how I can get my redo coins off etherscan please

**Comment by CriminalPnut** [comment]
Do you remember all your access information and all your phrase works and your wallet won't open it

**Comment by chrispy1174** [comment]
Correct

**Comment by vudieuls** [comment]
YES

Vào Th 2, 9 thg 8, 2021 vào lúc 08:43 chrispy1174 <
***@***.***> đã viết:

> Correct
>
> Sent from my iPhone
>

**Comment by chrispy1174** [comment]
Yes you will help? Please I need something good to happen for me

**Comment by CriminalPnut** [comment]
I can try my best I'm new at this myself but we can always take a look and
see what we can find

**Comment by chrispy1174** [comment]
I would be greatful but it’s my bed time. What’s a good role tomorrow?

**Review by Maxblinder — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Comment by maxtrem271991** [comment]
f368cd0ac7ac21755235719b63ac5d09718f6e74

**Review by maxtrem271991 — APPROVED** [review]

**Review by Maxblinder — APPROVED** [review]

**Comment by Maxblinder** [comment]
[README.md](https://github.com/dypfinance/staking-governance-security-audits/files/7043013/README.md)

**Review by Maxblinder — APPROVED** [review]

**Review by maxtrem271991 — APPROVED** [review]

**Review by maxtrem271991 — APPROVED** [review]

**Review by maxtrem271991 — APPROVED** [review]

**Review by maxtrem271991 — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by OutLAw-Dev — APPROVED** [review]

**Review by OutLAw-Dev — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Comment by zoeyteche** [comment]
Zoeyw637&gmail.com

[Zoey Willam - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=175j2m)	[175j2m]

On September 9, 2021 at 13:32 GMT, Shahryarmohammadie ***@***.***> wrote:

@Shahryarmohammadie approved this pull request.

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]

**Review by Shahryarmohammadie — APPROVED** [review]
good

**Review by Shahryarmohammadie — APPROVED** [review]
good

**Comment by hieueuro** [comment]
Good

**Review by Shahryarmohammadie — APPROVED** [review]
0xfD778cA23E9668F43bBA435646e08257898a1C10

**Comment by hieueuro** [comment]
Ok good

**Review by inkabord — APPROVED** [review]

**Review by aminpsycho — APPROVED** [review]

**Review by aminpsycho — APPROVED** [review]

**Comment by aminpsycho** [comment]
theomart77:main

**Review by Tarkan122 — APPROVED** [review]

**Comment by Shahryarmohammadie643** [comment]
Good

**Review by aminpsycho — APPROVED** [review]

**Review by aminpsycho — APPROVED** [review]
Ok

**Comment by Shahryarmohammadie643** [comment]
Hi

**Review by icabyz12 — APPROVED** [review]

**Review by Pencab — APPROVED** [review]

**Review by Vic23M — APPROVED** [review]

**Review by Vic23M — APPROVED** [review]

**Review by Haditorbatian — APPROVED** [review]

**Comment by Haditorbatian** [comment]
Good job

**Comment by Hexe4017** [comment]
Top

**Review by John19847 — APPROVED** [review]

**Pull request closed without merging**
